name: Pull request tests
run-name: Pull request tests ${{ github.head_ref }}

on:
  pull_request:
    branches: [master]                 # Déclenche le workflow sur les PR visant master
    types: [opened, synchronize, reopened, ready_for_review]
    # Événements qui relancent les tests
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }} 
  # Empêche l’exécution simultanée de plusieurs runs pour une même PR
  cancel-in-progress: true

jobs:
  test-server:
    name: Server test
    runs-on: ubuntu-latest             # Machine Linux fournie par GitHub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4      # Récupère le code de la PR

      - name: Setup Nodejs
        uses: actions/setup-node@v4    # Installe Node.js
        with:
          node-version: 20             # Version utilisée

      - name: Install NPM packages
        run: npm ci                    # Installe les dépendances

      - name: ESlint
        run: npm run eslint            # Vérifie le code avec ESLint
