name: Run Tennis Bot
run-name: Automated Tennis Search
on:
  schedule:
    # Tous les jeudi à 7h59 heure française (6h UTC)
    - cron: '59 6 * * 4'  # 06:59 UTC = 07:59 heure de Paris
  workflow_dispatch: # permet de le lancer manuellement si besoin

jobs:
  run-tennis:
    name: Run tennis booking script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install NPM packages
        run: npm ci
      - name: ESlint
        run: npm run eslint
      - name: Run tennis script
        run: node index.js
